FROM crossbario/autobahn-python:cpy3

RUN apt-get update && apt-get install -y \
  python3 \
  postgresql-server-dev-all \
  python3-pip \
  supervisor \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY docker/entrypoint.sh /
COPY docker/supervisor/rest.conf /etc/supervisor/conf.d
COPY docker/.pypirc /root/
COPY docker/pip.conf /etc/


COPY src /src
WORKDIR /src
RUN pip3 install -e .

ENTRYPOINT ["/entrypoint.sh"]
